//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Вопросы> Вопросы { get; set; }
        public virtual DbSet<Дисциплина> Дисциплина { get; set; }
        public virtual DbSet<Дисциплина_Раздел> Дисциплина_Раздел { get; set; }
        public virtual DbSet<Ответы> Ответы { get; set; }
        public virtual DbSet<Раздел> Раздел { get; set; }
        public virtual DbSet<Тема> Тема { get; set; }
    }
}
